### ISSUE TITLE
file proto.py bCMD_NODST have a different name

### ISSUE THREAD

**Issue by gabrielecastellano** [Acreo/DoubleDecker#1]
Hi, i discovered that there is an incompatibility between file proto.py and broker.py, in fact the first call a costant bCMD_NODST while the second is calling it as bCMD_ERROR, so when you try to launch broker.py get an error. I've fixed it for me by simply renaming bCMD_ERROR into bCMD_NODST in the proto.py file, but please fix it on the repository!!

**Comment by BtPht** [comment]
Hi, this is mistake from us. We didn't make it clear enough but the broker.py is not really supported any longer. proto.py is used only in the client which is updated to the latest version of the broker in C.

If you don't explicitly need to use the broker in python for some reasons please let us know the reasons and we will consider updating it, otherwise we advise you to switch to the C version for the broker.

**Comment by gabrielecastellano** [comment]
Ok, switched to the C version of the broker.
Thanks for the clarification and the updated documentation.
